export const FETCHING_NEWS_REQUEST = 'FETCHING_NEWS_REQUEST';
export const FETCHING_NEWS_SUCCESS = 'FETCHING_NEWS_SUCCESS';
export const FETCHING_NEWS_FAILURE = 'FETCHING_NEWS_FAILURE';
export const LOAD_MORE_NEWS_SUCCESS = 'LOAD_MORE_NEWS_SUCCESS';
